apiVersion: v1
kind: Template
metadata:
  name: "config-map-template"
objects:

  - apiVersion: v1
    kind: ConfigMap
    metadata:
      name: "test-config-map"
    data:
      testconfig: |-
        some configuration text
        some other line of text
  - apiVersion: v1
    kind: Pod
    metadata:
      name: simple-pod
    spec:
      containers:
        - name: bash-pod
          image: bash
          command: ["bash"]
          args:
            - -c
            - cat /etc/someconfig/test.conf; while :; do echo '.'; sleep 30; done
          volumeMounts:
            - name: config-volume
              mountPath: /etc/someconfig/test.conf
              subPath: testconfig
      volumes:
        - name: config-volume
          configMap:
            name: test-config-map