apiVersion: v1
kind: Template
metadata:
  name: "config-map-template"
objects:

  - apiVersion: v1
    kind: ConfigMap
    metadata:
      name: "test-config-map"
    data:
      test: "123"
      test1: ${TEST_PARAM}

parameters:
  - displayName: Test Param
    name: TEST_PARAM
    value: "test123"